### ISSUE TITLE
resolve Stream error in module import

### ISSUE THREAD

**Issue by mojtabasji** [gajjartejas/react-native-lan-port-scanner#5]
hi there
i have problem with import module
i use expo and after install and add import line i get below error

`undefined Unable to resolve module stream from Drive_Path:\node_modules\readable-stream\readable.js: stream could not be found within the project or in these directories:
  node_modules\readable-stream\node_modules
  node_modules`
> 1 | var Stream = require('stream'); // hack to fix a circular dependency issue when used with browserify
    |                       ^
  2 | exports = module.exports = require('./lib/_stream_readable.js');
  3 | exports.Stream = Stream;

i find that stream not reachable in react native and should remove it according this issue: 
https://github.com/facebook/react-native/issues/33981#issuecomment-1158019745

**Comment by gajjartejas** [comment]
This issue has been addressed, it should work now.
